// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Herd.proto

package org.denovogroup.murmur.objects;

public final class HerdProtos {
  private HerdProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface HandshakeMessageOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional string publicDevieID = 1;
    /**
     * <code>optional string publicDevieID = 1;</code>
     */
    boolean hasPublicDevieID();
    /**
     * <code>optional string publicDevieID = 1;</code>
     */
    java.lang.String getPublicDevieID();
    /**
     * <code>optional string publicDevieID = 1;</code>
     */
    com.google.protobuf.ByteString
        getPublicDevieIDBytes();

    // optional int32 messageType = 2;
    /**
     * <code>optional int32 messageType = 2;</code>
     */
    boolean hasMessageType();
    /**
     * <code>optional int32 messageType = 2;</code>
     */
    int getMessageType();
  }
  /**
   * Protobuf type {@code HandshakeMessage}
   */
  public static final class HandshakeMessage extends
      com.google.protobuf.GeneratedMessage
      implements HandshakeMessageOrBuilder {
    // Use HandshakeMessage.newBuilder() to construct.
    private HandshakeMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private HandshakeMessage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final HandshakeMessage defaultInstance;
    public static HandshakeMessage getDefaultInstance() {
      return defaultInstance;
    }

    public HandshakeMessage getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private HandshakeMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              publicDevieID_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              messageType_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.denovogroup.murmur.objects.HerdProtos.internal_static_HandshakeMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.denovogroup.murmur.objects.HerdProtos.internal_static_HandshakeMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.denovogroup.murmur.objects.HerdProtos.HandshakeMessage.class, org.denovogroup.murmur.objects.HerdProtos.HandshakeMessage.Builder.class);
    }

    public static com.google.protobuf.Parser<HandshakeMessage> PARSER =
        new com.google.protobuf.AbstractParser<HandshakeMessage>() {
      public HandshakeMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new HandshakeMessage(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<HandshakeMessage> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional string publicDevieID = 1;
    public static final int PUBLICDEVIEID_FIELD_NUMBER = 1;
    private java.lang.Object publicDevieID_;
    /**
     * <code>optional string publicDevieID = 1;</code>
     */
    public boolean hasPublicDevieID() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string publicDevieID = 1;</code>
     */
    public java.lang.String getPublicDevieID() {
      java.lang.Object ref = publicDevieID_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          publicDevieID_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string publicDevieID = 1;</code>
     */
    public com.google.protobuf.ByteString
        getPublicDevieIDBytes() {
      java.lang.Object ref = publicDevieID_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        publicDevieID_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional int32 messageType = 2;
    public static final int MESSAGETYPE_FIELD_NUMBER = 2;
    private int messageType_;
    /**
     * <code>optional int32 messageType = 2;</code>
     */
    public boolean hasMessageType() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 messageType = 2;</code>
     */
    public int getMessageType() {
      return messageType_;
    }

    private void initFields() {
      publicDevieID_ = "";
      messageType_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getPublicDevieIDBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, messageType_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getPublicDevieIDBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, messageType_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.denovogroup.murmur.objects.HerdProtos.HandshakeMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.denovogroup.murmur.objects.HerdProtos.HandshakeMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.denovogroup.murmur.objects.HerdProtos.HandshakeMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.denovogroup.murmur.objects.HerdProtos.HandshakeMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.denovogroup.murmur.objects.HerdProtos.HandshakeMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.denovogroup.murmur.objects.HerdProtos.HandshakeMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.denovogroup.murmur.objects.HerdProtos.HandshakeMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.denovogroup.murmur.objects.HerdProtos.HandshakeMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.denovogroup.murmur.objects.HerdProtos.HandshakeMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.denovogroup.murmur.objects.HerdProtos.HandshakeMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.denovogroup.murmur.objects.HerdProtos.HandshakeMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code HandshakeMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.denovogroup.murmur.objects.HerdProtos.HandshakeMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.denovogroup.murmur.objects.HerdProtos.internal_static_HandshakeMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.denovogroup.murmur.objects.HerdProtos.internal_static_HandshakeMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.denovogroup.murmur.objects.HerdProtos.HandshakeMessage.class, org.denovogroup.murmur.objects.HerdProtos.HandshakeMessage.Builder.class);
      }

      // Construct using org.denovogroup.murmur.objects.HerdProtos.HandshakeMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        publicDevieID_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        messageType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.denovogroup.murmur.objects.HerdProtos.internal_static_HandshakeMessage_descriptor;
      }

      public org.denovogroup.murmur.objects.HerdProtos.HandshakeMessage getDefaultInstanceForType() {
        return org.denovogroup.murmur.objects.HerdProtos.HandshakeMessage.getDefaultInstance();
      }

      public org.denovogroup.murmur.objects.HerdProtos.HandshakeMessage build() {
        org.denovogroup.murmur.objects.HerdProtos.HandshakeMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.denovogroup.murmur.objects.HerdProtos.HandshakeMessage buildPartial() {
        org.denovogroup.murmur.objects.HerdProtos.HandshakeMessage result = new org.denovogroup.murmur.objects.HerdProtos.HandshakeMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.publicDevieID_ = publicDevieID_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.messageType_ = messageType_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.denovogroup.murmur.objects.HerdProtos.HandshakeMessage) {
          return mergeFrom((org.denovogroup.murmur.objects.HerdProtos.HandshakeMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.denovogroup.murmur.objects.HerdProtos.HandshakeMessage other) {
        if (other == org.denovogroup.murmur.objects.HerdProtos.HandshakeMessage.getDefaultInstance()) return this;
        if (other.hasPublicDevieID()) {
          bitField0_ |= 0x00000001;
          publicDevieID_ = other.publicDevieID_;
          onChanged();
        }
        if (other.hasMessageType()) {
          setMessageType(other.getMessageType());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.denovogroup.murmur.objects.HerdProtos.HandshakeMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.denovogroup.murmur.objects.HerdProtos.HandshakeMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional string publicDevieID = 1;
      private java.lang.Object publicDevieID_ = "";
      /**
       * <code>optional string publicDevieID = 1;</code>
       */
      public boolean hasPublicDevieID() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string publicDevieID = 1;</code>
       */
      public java.lang.String getPublicDevieID() {
        java.lang.Object ref = publicDevieID_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          publicDevieID_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string publicDevieID = 1;</code>
       */
      public com.google.protobuf.ByteString
          getPublicDevieIDBytes() {
        java.lang.Object ref = publicDevieID_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          publicDevieID_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string publicDevieID = 1;</code>
       */
      public Builder setPublicDevieID(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        publicDevieID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string publicDevieID = 1;</code>
       */
      public Builder clearPublicDevieID() {
        bitField0_ = (bitField0_ & ~0x00000001);
        publicDevieID_ = getDefaultInstance().getPublicDevieID();
        onChanged();
        return this;
      }
      /**
       * <code>optional string publicDevieID = 1;</code>
       */
      public Builder setPublicDevieIDBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        publicDevieID_ = value;
        onChanged();
        return this;
      }

      // optional int32 messageType = 2;
      private int messageType_ ;
      /**
       * <code>optional int32 messageType = 2;</code>
       */
      public boolean hasMessageType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 messageType = 2;</code>
       */
      public int getMessageType() {
        return messageType_;
      }
      /**
       * <code>optional int32 messageType = 2;</code>
       */
      public Builder setMessageType(int value) {
        bitField0_ |= 0x00000002;
        messageType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 messageType = 2;</code>
       */
      public Builder clearMessageType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        messageType_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:HandshakeMessage)
    }

    static {
      defaultInstance = new HandshakeMessage(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:HandshakeMessage)
  }

  public interface HerdPacketOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional string destination = 1;
    /**
     * <code>optional string destination = 1;</code>
     */
    boolean hasDestination();
    /**
     * <code>optional string destination = 1;</code>
     */
    java.lang.String getDestination();
    /**
     * <code>optional string destination = 1;</code>
     */
    com.google.protobuf.ByteString
        getDestinationBytes();

    // optional string payload = 2;
    /**
     * <code>optional string payload = 2;</code>
     */
    boolean hasPayload();
    /**
     * <code>optional string payload = 2;</code>
     */
    java.lang.String getPayload();
    /**
     * <code>optional string payload = 2;</code>
     */
    com.google.protobuf.ByteString
        getPayloadBytes();
  }
  /**
   * Protobuf type {@code HerdPacket}
   */
  public static final class HerdPacket extends
      com.google.protobuf.GeneratedMessage
      implements HerdPacketOrBuilder {
    // Use HerdPacket.newBuilder() to construct.
    private HerdPacket(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private HerdPacket(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final HerdPacket defaultInstance;
    public static HerdPacket getDefaultInstance() {
      return defaultInstance;
    }

    public HerdPacket getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private HerdPacket(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              destination_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              payload_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.denovogroup.murmur.objects.HerdProtos.internal_static_HerdPacket_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.denovogroup.murmur.objects.HerdProtos.internal_static_HerdPacket_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.denovogroup.murmur.objects.HerdProtos.HerdPacket.class, org.denovogroup.murmur.objects.HerdProtos.HerdPacket.Builder.class);
    }

    public static com.google.protobuf.Parser<HerdPacket> PARSER =
        new com.google.protobuf.AbstractParser<HerdPacket>() {
      public HerdPacket parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new HerdPacket(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<HerdPacket> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional string destination = 1;
    public static final int DESTINATION_FIELD_NUMBER = 1;
    private java.lang.Object destination_;
    /**
     * <code>optional string destination = 1;</code>
     */
    public boolean hasDestination() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string destination = 1;</code>
     */
    public java.lang.String getDestination() {
      java.lang.Object ref = destination_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          destination_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string destination = 1;</code>
     */
    public com.google.protobuf.ByteString
        getDestinationBytes() {
      java.lang.Object ref = destination_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        destination_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string payload = 2;
    public static final int PAYLOAD_FIELD_NUMBER = 2;
    private java.lang.Object payload_;
    /**
     * <code>optional string payload = 2;</code>
     */
    public boolean hasPayload() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string payload = 2;</code>
     */
    public java.lang.String getPayload() {
      java.lang.Object ref = payload_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          payload_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string payload = 2;</code>
     */
    public com.google.protobuf.ByteString
        getPayloadBytes() {
      java.lang.Object ref = payload_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        payload_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      destination_ = "";
      payload_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getDestinationBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getPayloadBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getDestinationBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getPayloadBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static org.denovogroup.murmur.objects.HerdProtos.HerdPacket parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.denovogroup.murmur.objects.HerdProtos.HerdPacket parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.denovogroup.murmur.objects.HerdProtos.HerdPacket parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.denovogroup.murmur.objects.HerdProtos.HerdPacket parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.denovogroup.murmur.objects.HerdProtos.HerdPacket parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.denovogroup.murmur.objects.HerdProtos.HerdPacket parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.denovogroup.murmur.objects.HerdProtos.HerdPacket parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.denovogroup.murmur.objects.HerdProtos.HerdPacket parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.denovogroup.murmur.objects.HerdProtos.HerdPacket parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.denovogroup.murmur.objects.HerdProtos.HerdPacket parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.denovogroup.murmur.objects.HerdProtos.HerdPacket prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code HerdPacket}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.denovogroup.murmur.objects.HerdProtos.HerdPacketOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.denovogroup.murmur.objects.HerdProtos.internal_static_HerdPacket_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.denovogroup.murmur.objects.HerdProtos.internal_static_HerdPacket_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.denovogroup.murmur.objects.HerdProtos.HerdPacket.class, org.denovogroup.murmur.objects.HerdProtos.HerdPacket.Builder.class);
      }

      // Construct using org.denovogroup.murmur.objects.HerdProtos.HerdPacket.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        destination_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        payload_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.denovogroup.murmur.objects.HerdProtos.internal_static_HerdPacket_descriptor;
      }

      public org.denovogroup.murmur.objects.HerdProtos.HerdPacket getDefaultInstanceForType() {
        return org.denovogroup.murmur.objects.HerdProtos.HerdPacket.getDefaultInstance();
      }

      public org.denovogroup.murmur.objects.HerdProtos.HerdPacket build() {
        org.denovogroup.murmur.objects.HerdProtos.HerdPacket result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.denovogroup.murmur.objects.HerdProtos.HerdPacket buildPartial() {
        org.denovogroup.murmur.objects.HerdProtos.HerdPacket result = new org.denovogroup.murmur.objects.HerdProtos.HerdPacket(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.destination_ = destination_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.payload_ = payload_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.denovogroup.murmur.objects.HerdProtos.HerdPacket) {
          return mergeFrom((org.denovogroup.murmur.objects.HerdProtos.HerdPacket)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.denovogroup.murmur.objects.HerdProtos.HerdPacket other) {
        if (other == org.denovogroup.murmur.objects.HerdProtos.HerdPacket.getDefaultInstance()) return this;
        if (other.hasDestination()) {
          bitField0_ |= 0x00000001;
          destination_ = other.destination_;
          onChanged();
        }
        if (other.hasPayload()) {
          bitField0_ |= 0x00000002;
          payload_ = other.payload_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.denovogroup.murmur.objects.HerdProtos.HerdPacket parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.denovogroup.murmur.objects.HerdProtos.HerdPacket) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional string destination = 1;
      private java.lang.Object destination_ = "";
      /**
       * <code>optional string destination = 1;</code>
       */
      public boolean hasDestination() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string destination = 1;</code>
       */
      public java.lang.String getDestination() {
        java.lang.Object ref = destination_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          destination_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string destination = 1;</code>
       */
      public com.google.protobuf.ByteString
          getDestinationBytes() {
        java.lang.Object ref = destination_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          destination_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string destination = 1;</code>
       */
      public Builder setDestination(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        destination_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string destination = 1;</code>
       */
      public Builder clearDestination() {
        bitField0_ = (bitField0_ & ~0x00000001);
        destination_ = getDefaultInstance().getDestination();
        onChanged();
        return this;
      }
      /**
       * <code>optional string destination = 1;</code>
       */
      public Builder setDestinationBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        destination_ = value;
        onChanged();
        return this;
      }

      // optional string payload = 2;
      private java.lang.Object payload_ = "";
      /**
       * <code>optional string payload = 2;</code>
       */
      public boolean hasPayload() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string payload = 2;</code>
       */
      public java.lang.String getPayload() {
        java.lang.Object ref = payload_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          payload_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string payload = 2;</code>
       */
      public com.google.protobuf.ByteString
          getPayloadBytes() {
        java.lang.Object ref = payload_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          payload_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string payload = 2;</code>
       */
      public Builder setPayload(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        payload_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string payload = 2;</code>
       */
      public Builder clearPayload() {
        bitField0_ = (bitField0_ & ~0x00000002);
        payload_ = getDefaultInstance().getPayload();
        onChanged();
        return this;
      }
      /**
       * <code>optional string payload = 2;</code>
       */
      public Builder setPayloadBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        payload_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:HerdPacket)
    }

    static {
      defaultInstance = new HerdPacket(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:HerdPacket)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_HandshakeMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_HandshakeMessage_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_HerdPacket_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_HerdPacket_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nHerd.proto\">\n\020HandshakeMessage\022\025\n\rpubl" +
      "icDevieID\030\001 \001(\t\022\023\n\013messageType\030\002 \001(\005\"2\n\n" +
      "HerdPacket\022\023\n\013destination\030\001 \001(\t\022\017\n\007paylo" +
      "ad\030\002 \001(\tB,\n\036org.denovogroup.murmur.objec" +
      "tsB\nHerdProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_HandshakeMessage_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_HandshakeMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_HandshakeMessage_descriptor,
              new java.lang.String[] { "PublicDevieID", "MessageType", });
          internal_static_HerdPacket_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_HerdPacket_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_HerdPacket_descriptor,
              new java.lang.String[] { "Destination", "Payload", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
